In [3]:
import numpy as np

In [ ]:
def x(a,b):
    return a+b

In [2]:
x([1,2,3],[4,5,6])

[1, 2, 3, 4, 5, 6]

In [4]:
def x(a,b):
    return [i+j for i,j in zip(a,b)]

In [7]:
x([1,2,3],[4,5,6])

[5, 7, 9]

In [8]:
@np.vectorize
def z(a,b):
    return a+b

In [9]:
z([1,2,3],[4,5,6])

array([5, 7, 9])

In [22]:
x = np.array([[1,2,3],[4,5,6],[7,8,9]])

In [23]:
x

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [14]:
np.sum(x[0])

6

In [27]:
np.sum(x,axis = 1)  #행 부분 계산

array([ 6, 15, 24])

In [28]:
np.sum(x,axis = 0)  #열 부분 계산

array([12, 15, 18])

In [30]:
np.sum(x) #axis를 안붙혀주면 전체값을 계산한다.

45

In [31]:
a = np.arange(10)

In [32]:
a

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [33]:
a = np.arange(10).reshape(2,5)

In [34]:
a

array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9]])

In [39]:
a = np.arange(10).reshape(5,2)

In [40]:
a

array([[0, 1],
       [2, 3],
       [4, 5],
       [6, 7],
       [8, 9]])

In [43]:
a = np.arange(10).reshape(-1,5)  #-1: 자동으로바꿔준다.

In [44]:
a

array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9]])

다음파일