In [5]:
import numpy as np #먼저 import한다. 벡터기반(공간의 특정점을 표시할수 있는애)

0차는 스칼라 벡터는 1차원 행렬은 2차원 3차원 벡터는 tensor

In [4]:
import array

In [6]:
a = np.array(0) #스칼라

In [7]:
a #결과에 array라고 나온거는 numpy형태 라고한다.

array(0)

In [8]:
type(a)

numpy.ndarray

In [9]:
a = np.array([1,2])

In [10]:
a

array([1, 2])

In [11]:
a = np.array([[1,2],[2,3]]) #2차원 벡터

In [12]:
a

array([[1, 2],
       [2, 3]])

In [16]:
a = np.array([[[1,2],[3,4],[5,6]]]) #3차원 벡터

In [17]:
a

array([[[1, 2],
        [3, 4],
        [5, 6]]])

In [18]:
b = np.zeros([3,3]) #영행렬

In [19]:
b

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [22]:
c = np.eye(3) #단위행렬

In [21]:
c

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [23]:
c[0]

array([1., 0., 0.])

In [24]:
c[1]

array([0., 1., 0.])

In [25]:
c[2]

array([0., 0., 1.])

In [30]:
c[0][0]

1.0

In [31]:
a = np.array([[1,2],[3,4],[5,6]])

In [33]:
a #3행2열 행렬

array([[1, 2],
       [3, 4],
       [5, 6]])

In [35]:
a.T #행과 열을 바꿔준다.

array([[1, 3, 5],
       [2, 4, 6]])