## ufunc

In [7]:
import numpy as np

In [8]:
import math

In [5]:
np.sum(range(100))

4950

In [6]:
np.sqrt(4)

2.0

In [11]:
math.sqrt(4)

2.0

In [12]:
math.sqrt([4,9])

TypeError: must be real number, not list

In [10]:
np.sqrt([4,9])

array([2., 3.])

In [13]:
np.sqrt((4,9))

array([2., 3.])

In [14]:
np.info()

 info(object=None, maxwidth=76,
      output=<ipykernel.iostream.OutStream object at 0x000002223E411780>,
      toplevel='numpy')

Get help information for a function, class, or module.

Parameters
----------
object : object or str, optional
    Input object or name to get information about. If `object` is a
    numpy object, its docstring is given. If it is a string, available
    modules are searched for matching objects.  If None, information
    about `info` itself is returned.
maxwidth : int, optional
    Printing width.
output : file like object, optional
    File like object that the output is written to, default is
    ``stdout``.  The object has to be opened in 'w' or 'a' mode.
toplevel : str, optional
    Start search at this level.

See Also
--------
source, lookfor

Notes
-----
When used interactively with an object, ``np.info(obj)`` is equivalent
to ``help(obj)`` on the Python prompt or ``obj?`` on the IPython
prompt.

Examples
--------
>>> np.info(np.polyval) # doctest: +

In [19]:
np.add([1,2],[4,5])

array([5, 7])

In [20]:
x = np.array([2,2])

In [22]:
np.dot(x,x)

8

In [23]:
x.dot(x)

8

In [24]:
type(np.dot)

builtin_function_or_method

---

shape

다음파일