In [1]:
import numpy as np

In [3]:
a = np.arange(36).reshape(6,6)

In [4]:
a

array([[ 0,  1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10, 11],
       [12, 13, 14, 15, 16, 17],
       [18, 19, 20, 21, 22, 23],
       [24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35]])

In [5]:
a[0,3:5]

array([3, 4])

In [32]:
a[4:,4:]

array([[28, 29],
       [34, 35]])

In [34]:
a[-2:,-2:]

array([[28, 29],
       [34, 35]])

In [36]:
a[[-2,-1],[-2,-1]]

array([28, 35])

In [7]:
a[:,2]

array([ 2,  8, 14, 20, 26, 32])

In [37]:
a[2::2,::2]

array([[12, 14, 16],
       [24, 26, 28]])

In [43]:
a[[2,4]][:,::2]

array([[12, 14, 16],
       [24, 26, 28]])

In [46]:
a[[True,False,True,False,True,False]]

array([[ 0,  1,  2,  3,  4,  5],
       [12, 13, 14, 15, 16, 17],
       [24, 25, 26, 27, 28, 29]])

In [48]:
a[np.ix_([0,2,4],[0,2])]

array([[ 0,  2],
       [12, 14],
       [24, 26]])

In [49]:
a[np.ix_([2,4],[0,2,4])]

array([[12, 14, 16],
       [24, 26, 28]])

In [9]:
a[(0,1,2,3,4),(1,2,3,4,5)]

array([ 1,  8, 15, 22, 29])

In [10]:
a[3:,[0,2,5]]

array([[18, 20, 23],
       [24, 26, 29],
       [30, 32, 35]])

In [15]:
b = np.arange(25).reshape(5,5)

In [16]:
b

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])

In [23]:
b[0]

array([0, 1, 2, 3, 4])

In [24]:
b[1,3:5]

array([8, 9])

In [25]:
b[:,4]

array([ 4,  9, 14, 19, 24])

In [26]:
b[-2:,-2:]

array([[18, 19],
       [23, 24]])

In [27]:
b[2::2, ::2]

array([[10, 12, 14],
       [20, 22, 24]])

In [28]:
b[0,1]

1

In [29]:
b[[0,1]]

array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9]])

In [30]:
b[[1,2,4],[2,3,4]]

array([ 7, 13, 24])

In [31]:
b[3:,[0,1,3]]

array([[15, 16, 18],
       [20, 21, 23]])

In [51]:
from collections import namedtuple #이름있는 tuple 

In [56]:
t = namedtuple('AttendanceSheet',['name','attendance'])

In [57]:
x = t('moon','yes')

In [60]:
x[0]

'moon'

In [61]:
x[1]

'yes'

In [62]:
x.name

'moon'

In [63]:
type(x)

__main__.AttendanceSheet

---

broadcasting

---

In [67]:
a = np.arange(10)

In [68]:
a

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [70]:
b = a + 1

In [71]:
b

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [72]:
a

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])