In [9]:
a = [1,2,3]

In [2]:
b = a

In [3]:
b.append(4)

In [4]:
a

[1, 2, 3, 4]

In [5]:
b

[1, 2, 3, 4]

In [10]:
b = a.copy()

In [11]:
b.append(4)

In [12]:
a

[1, 2, 3]

In [41]:
b

[[1, 4, 3]]

In [49]:
import copy
import numpy as np

In [37]:
a = [[1,2,3]]

In [38]:
b = a.copy()

In [39]:
a[0][1] = 4

In [40]:
b

[[1, 4, 3]]

In [43]:
a = [[1,2,3]]

In [45]:
b = copy.deepcopy(a)

In [46]:
a[0][1] = 4

In [47]:
b

[[1, 2, 3]]

In [54]:
a = np.array([[1,2,3],[4,5,6]])

In [55]:
b = a.copy()

In [56]:
a[0][0] = 4

In [57]:
b

array([[1, 2, 3],
       [4, 5, 6]])

In [58]:
a = np.arange(10).reshape(2,5)

In [59]:
a.ravel()  #

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [60]:
a.flatten() #copy

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [62]:
c = np.arange(10).reshape(2,5)

In [63]:
c

array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9]])

In [64]:
c.T

array([[0, 5],
       [1, 6],
       [2, 7],
       [3, 8],
       [4, 9]])