In [1]:
def x():
    for i in range(10):
        print(i)

In [2]:
import dis

In [4]:
dis.dis(x)

  2           0 SETUP_LOOP              24 (to 26)
              2 LOAD_GLOBAL              0 (range)
              4 LOAD_CONST               1 (10)
              6 CALL_FUNCTION            1
              8 GET_ITER
        >>   10 FOR_ITER                12 (to 24)
             12 STORE_FAST               0 (i)

  3          14 LOAD_GLOBAL              1 (print)
             16 LOAD_FAST                0 (i)
             18 CALL_FUNCTION            1
             20 POP_TOP
             22 JUMP_ABSOLUTE           10
        >>   24 POP_BLOCK
        >>   26 LOAD_CONST               0 (None)
             28 RETURN_VALUE


In [5]:
import numpy as np

In [8]:
a = np.array([1,2,3])

In [9]:
a

array([1, 2, 3])

In [11]:
a[np.newaxis]

array([[1, 2, 3]])

In [12]:
a[:,np.newaxis]

array([[1],
       [2],
       [3]])

In [13]:
a = np.array([[1,2,3],[4,5,6]])

In [14]:
a[np.newaxis]

array([[[1, 2, 3],
        [4, 5, 6]]])

In [17]:
a[:,np.newaxis]

array([[[1, 2, 3]],

       [[4, 5, 6]]])

In [18]:
a[:,np.newaxis].shape

(2, 1, 3)

In [16]:
a[:,:,np.newaxis]

array([[[1],
        [2],
        [3]],

       [[4],
        [5],
        [6]]])

In [22]:
a = np.array([1,2,3])

In [23]:
np.tile(a,[2,3])

array([[1, 2, 3, 1, 2, 3, 1, 2, 3],
       [1, 2, 3, 1, 2, 3, 1, 2, 3]])

In [21]:
np.tile(a,(2,3))

array([[1, 2, 3, 1, 2, 3, 1, 2, 3],
       [1, 2, 3, 1, 2, 3, 1, 2, 3]])

In [35]:
%%writefile t.csv
1,2,3
4,5,6

Overwriting t.csv


In [31]:
x = np.loadtxt('t.csv',delimiter=',')  #txt 텍스트파일을 로드해서 넘파이 형태로 만들어준다. 

In [32]:
x

array([[1., 2., 3.],
       [4., 5., 6.]])

In [38]:
x = np.genfromtxt('t.csv',delimiter=',')

In [39]:
x

array([[1., 2., 3.],
       [4., 5., 6.]])