In [6]:
import numpy as np

In [7]:
%%writefile t.csv
1,2,3
4,5,6

Overwriting t.csv


In [8]:
y = np.fromfile('t.csv',sep=',')

In [10]:
y

array([1., 2., 3.])

In [33]:
x = np.array([[1,2,3],[4,5,6]])

In [34]:
x

array([[1, 2, 3],
       [4, 5, 6]])

In [21]:
np.savez('x.npz',x)

In [14]:
s = np.load('x.npz')

In [15]:
s

In [35]:
np.save('tttt',x)

In [36]:
s = np.load('tttt.npy')

In [37]:
s

array([[1, 2, 3],
       [4, 5, 6]])

In [38]:
import pickle

In [39]:
with open('sun.ss','wb') as f:
    pickle.dump(s,f)

In [40]:
with open('sun.ss','rb') as f:
    ss = pickle.load(f)

In [41]:
ss

array([[1, 2, 3],
       [4, 5, 6]])

In [ ]:
np.savez