In [13]:
import seaborn as sns
import pandas as pd

In [6]:
data = sns.load_dataset('iris')

In [14]:
pd.get_dummies(data.species)

setosa  versicolor  virginica
0         1           0          0
1         1           0          0
2         1           0          0
3         1           0          0
4         1           0          0
5         1           0          0
6         1           0          0
7         1           0          0
8         1           0          0
9         1           0          0
10        1           0          0
11        1           0          0
12        1           0          0
13        1           0          0
14        1           0          0
15        1           0          0
16        1           0          0
17        1           0          0
18        1           0          0
19        1           0          0
20        1           0          0
21        1           0          0
22        1           0          0
23        1           0          0
24        1           0          0
25        1           0          0
26        1           0          0
27        1           0          0
28        1           0          0
29        1           0          0
..      ...         ...        ...
120       0           0          1
121       0           0          1
122       0           0          1
123       0           0          1
124       0           0          1
125       0           0          1
126       0           0          1
127       0           0          1
128       0           0          1
129       0           0          1
130       0           0          1
131       0           0          1
132       0           0          1
133       0           0          1
134       0           0          1
135       0           0          1
136       0           0          1
137       0           0          1
138       0           0          1
139       0           0          1
140       0           0          1
141       0           0          1
142       0           0          1
143       0           0          1
144       0           0          1
145       0           0          1
146       0           0          1
147       0           0          1
148       0           0          1
149       0           0          1

[150 rows x 3 columns]

In [15]:
from sklearn.preprocessing import OneHotEncoder #문자를 숫자를 바꿔줘야한다.

In [16]:
ohe = OneHotEncoder() #인스턴스한다.

In [26]:
ohe.fit(data[['species']]) 

OneHotEncoder(categorical_features=None, categories=None,
       dtype=<class 'numpy.float64'>, handle_unknown='error',
       n_values=None, sparse=True)

In [27]:
ohe.transform(data[['species']])

<150x3 sparse matrix of type '<class 'numpy.float64'>'
	with 150 stored elements in Compressed Sparse Row format>

In [21]:
t = ohe.transform(data[['species']])

In [22]:
t.toarray()

array([[1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0

In [28]:
ohe.fit_transform(data[['species']]).toarray()

array([[1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0

In [29]:
ohe.inverse_transform([[1., 0., 0.]])

array([['setosa']], dtype=object)

In [30]:
from sklearn.preprocessing import LabelEncoder

In [31]:
le = LabelEncoder()

In [33]:
le.fit_transform(data.species)

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
       2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
       2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2])

In [35]:
x = pd.DataFrame(le.fit_transform(data.species), columns=['target'])

In [36]:
x

target
0         0
1         0
2         0
3         0
4         0
5         0
6         0
7         0
8         0
9         0
10        0
11        0
12        0
13        0
14        0
15        0
16        0
17        0
18        0
19        0
20        0
21        0
22        0
23        0
24        0
25        0
26        0
27        0
28        0
29        0
..      ...
120       2
121       2
122       2
123       2
124       2
125       2
126       2
127       2
128       2
129       2
130       2
131       2
132       2
133       2
134       2
135       2
136       2
137       2
138       2
139       2
140       2
141       2
142       2
143       2
144       2
145       2
146       2
147       2
148       2
149       2

[150 rows x 1 columns]

In [39]:
data_pd = pd.concat([data,x],axis = 1) #iris 데이터 뒤에 합친다.

In [40]:
data_pd

sepal_length  sepal_width  petal_length  petal_width    species  target
0             5.1          3.5           1.4          0.2     setosa       0
1             4.9          3.0           1.4          0.2     setosa       0
2             4.7          3.2           1.3          0.2     setosa       0
3             4.6          3.1           1.5          0.2     setosa       0
4             5.0          3.6           1.4          0.2     setosa       0
5             5.4          3.9           1.7          0.4     setosa       0
6             4.6          3.4           1.4          0.3     setosa       0
7             5.0          3.4           1.5          0.2     setosa       0
8             4.4          2.9           1.4          0.2     setosa       0
9             4.9          3.1           1.5          0.1     setosa       0
10            5.4          3.7           1.5          0.2     setosa       0
11            4.8          3.4           1.6          0.2     setosa       0
12            4.8          3.0           1.4          0.1     setosa       0
13            4.3          3.0           1.1          0.1     setosa       0
14            5.8          4.0           1.2          0.2     setosa       0
15            5.7          4.4           1.5          0.4     setosa       0
16            5.4          3.9           1.3          0.4     setosa       0
17            5.1          3.5           1.4          0.3     setosa       0
18            5.7          3.8           1.7          0.3     setosa       0
19            5.1          3.8           1.5          0.3     setosa       0
20            5.4          3.4           1.7          0.2     setosa       0
21            5.1          3.7           1.5          0.4     setosa       0
22            4.6          3.6           1.0          0.2     setosa       0
23            5.1          3.3           1.7          0.5     setosa       0
24            4.8          3.4           1.9          0.2     setosa       0
25            5.0          3.0           1.6          0.2     setosa       0
26            5.0          3.4           1.6          0.4     setosa       0
27            5.2          3.5           1.5          0.2     setosa       0
28            5.2          3.4           1.4          0.2     setosa       0
29            4.7          3.2           1.6          0.2     setosa       0
..            ...          ...           ...          ...        ...     ...
120           6.9          3.2           5.7          2.3  virginica       2
121           5.6          2.8           4.9          2.0  virginica       2
122           7.7          2.8           6.7          2.0  virginica       2
123           6.3          2.7           4.9          1.8  virginica       2
124           6.7          3.3           5.7          2.1  virginica       2
125           7.2          3.2           6.0          1.8  virginica       2
126           6.2          2.8           4.8          1.8  virginica       2
127           6.1          3.0           4.9          1.8  virginica       2
128           6.4          2.8           5.6          2.1  virginica       2
129           7.2          3.0           5.8          1.6  virginica       2
130           7.4          2.8           6.1          1.9  virginica       2
131           7.9          3.8           6.4          2.0  virginica       2
132           6.4          2.8           5.6          2.2  virginica       2
133           6.3          2.8           5.1          1.5  virginica       2
134           6.1          2.6           5.6          1.4  virginica       2
135           7.7          3.0           6.1          2.3  virginica       2
136           6.3          3.4           5.6          2.4  virginica       2
137           6.4          3.1           5.5          1.8  virginica       2
138           6.0          3.0           4.8          1.8  virginica       2
139           6.9          3.1           5.4          2.1  virginica       2
1

In [41]:
from sklearn.model_selection import train_test_split

In [43]:
X_train, X_test,y_train,y_test = train_test_split(data_pd[data_pd.columns[:-2]], data_pd.target)

In [44]:
X_train

sepal_length  sepal_width  petal_length  petal_width
148           6.2          3.4           5.4          2.3
136           6.3          3.4           5.6          2.4
94            5.6          2.7           4.2          1.3
59            5.2          2.7           3.9          1.4
121           5.6          2.8           4.9          2.0
126           6.2          2.8           4.8          1.8
108           6.7          2.5           5.8          1.8
85            6.0          3.4           4.5          1.6
106           4.9          2.5           4.5          1.7
93            5.0          2.3           3.3          1.0
41            4.5          2.3           1.3          0.3
14            5.8          4.0           1.2          0.2
112           6.8          3.0           5.5          2.1
11            4.8          3.4           1.6          0.2
63            6.1          2.9           4.7          1.4
29            4.7          3.2           1.6          0.2
76            6.8          2.8           4.8          1.4
100           6.3          3.3           6.0          2.5
8             4.4          2.9           1.4          0.2
2             4.7          3.2           1.3          0.2
107           7.3          2.9           6.3          1.8
49            5.0          3.3           1.4          0.2
20            5.4          3.4           1.7          0.2
69            5.6          2.5           3.9          1.1
34            4.9          3.1           1.5          0.2
144           6.7          3.3           5.7          2.5
31            5.4          3.4           1.5          0.4
66            5.6          3.0           4.5          1.5
99            5.7          2.8           4.1          1.3
30            4.8          3.1           1.6          0.2
..            ...          ...           ...          ...
109           7.2          3.6           6.1          2.5
19            5.1          3.8           1.5          0.3
23            5.1          3.3           1.7          0.5
4             5.0          3.6           1.4          0.2
125           7.2          3.2           6.0          1.8
32            5.2          4.1           1.5          0.1
141           6.9          3.1           5.1          2.3
119           6.0          2.2           5.0          1.5
16            5.4          3.9           1.3          0.4
35            5.0          3.2           1.2          0.2
116           6.5          3.0           5.5          1.8
89            5.5          2.5           4.0          1.3
96            5.7          2.9           4.2          1.3
5             5.4          3.9           1.7          0.4
101           5.8          2.7           5.1          1.9
22            4.6          3.6           1.0          0.2
43            5.0          3.5           1.6          0.6
12            4.8          3.0           1.4          0.1
146           6.3          2.5           5.0          1.9
105           7.6          3.0           6.6          2.1
39            5.1          3.4           1.5          0.2
128           6.4          2.8           5.6          2.1
120           6.9          3.2           5.7          2.3
118           7.7          2.6           6.9          2.3
42            4.4          3.2           1.3          0.2
45            4.8          3.0           1.4          0.3
134           6.1          2.6           5.6          1.4
36            5.5          3.5           1.3          0.2
111           6.4          2.7           5.3          1.9
3             4.6          3.1           1.5          0.2

[112 rows x 4 columns]

holdout

data leakage

cross-validation - 대충 성능파악,하이퍼파라미터 찾을때

k-fold

In [46]:
from sklearn.neighbors import KNeighborsClassifier

In [47]:
knn = KNeighborsClassifier()

In [48]:
knn.fit(X_train,y_train)

KNeighborsClassifier(algorithm='auto', leaf_size=30, metric='minkowski',
           metric_params=None, n_jobs=None, n_neighbors=5, p=2,
           weights='uniform')

In [49]:
knn.score(X_test,y_test) #정확도를 나타낸다.

0.9473684210526315

In [50]:
knn5 = KNeighborsClassifier(5)
knn7 = KNeighborsClassifier(7)

In [51]:
knn5.fit(X_train,y_train)
knn7.fit(X_train,y_train)

KNeighborsClassifier(algorithm='auto', leaf_size=30, metric='minkowski',
           metric_params=None, n_jobs=None, n_neighbors=7, p=2,
           weights='uniform')

In [53]:
knn5.score(X_test,y_test) #정확도를 나타낸다.
# knn7.score(X_test,y_test) #정확도를 나타낸다.

0.9473684210526315

In [55]:
from sklearn.model_selection import cross_val_score

In [56]:
r = KNeighborsClassifier()

In [60]:
c = cross_val_score(r,data_pd[data_pd.columns[:-2]],data_pd.target,cv=10)

In [61]:
c

array([1.        , 0.93333333, 1.        , 1.        , 0.86666667,
       0.93333333, 0.93333333, 1.        , 1.        , 1.        ])

In [58]:
import numpy as np

In [62]:
np.mean(c)

0.9666666666666668

In [64]:
temp=[]
for i,j in enumerate(range(20)):
    r = KNeighborsClassifier(i+3)
    c = cross_val_score(r,data_pd[data_pd.columns[:-2]],data_pd.target,cv=10)
    temp.append(np.mean(c))

In [65]:
np.max(temp)

0.9800000000000001

In [66]:
b = np.array(temp)

In [67]:
np.where(b==0.9800000000000001)

(array([10, 15, 17], dtype=int64),)

In [68]:
from sklearn.metrics import classification_report

In [70]:
print(classification_report(y_test,knn.predict(X_test)))

              precision    recall  f1-score   support

           0       1.00      1.00      1.00         9
           1       1.00      0.89      0.94        19
           2       0.83      1.00      0.91        10

   micro avg       0.95      0.95      0.95        38
   macro avg       0.94      0.96      0.95        38
weighted avg       0.96      0.95      0.95        38



In [71]:
from sklearn.linear_model import LogisticRegression

In [72]:
lr = LogisticRegression()

In [74]:
lr.fit(X_train,y_train)

C:\ProgramData\Anaconda3\lib\site-packages\sklearn\linear_model\logistic.py:433: FutureWarning: Default solver will be changed to 'lbfgs' in 0.22. Specify a solver to silence this warning.
  FutureWarning)
C:\ProgramData\Anaconda3\lib\site-packages\sklearn\linear_model\logistic.py:460: FutureWarning: Default multi_class will be changed to 'auto' in 0.22. Specify the multi_class option to silence this warning.
  "this warning.", FutureWarning)


LogisticRegression(C=1.0, class_weight=None, dual=False, fit_intercept=True,
          intercept_scaling=1, max_iter=100, multi_class='warn',
          n_jobs=None, penalty='l2', random_state=None, solver='warn',
          tol=0.0001, verbose=0, warm_start=False)

In [75]:
lr.score(X_test,y_test)

0.9210526315789473

In [83]:
cross_val_score(LogisticRegression(),data_pd.iloc[:,:-2],data_pd.target,cv=10).mean()

C:\ProgramData\Anaconda3\lib\site-packages\sklearn\linear_model\logistic.py:433: FutureWarning: Default solver will be changed to 'lbfgs' in 0.22. Specify a solver to silence this warning.
  FutureWarning)
C:\ProgramData\Anaconda3\lib\site-packages\sklearn\linear_model\logistic.py:460: FutureWarning: Default multi_class will be changed to 'auto' in 0.22. Specify the multi_class option to silence this warning.
  "this warning.", FutureWarning)
C:\ProgramData\Anaconda3\lib\site-packages\sklearn\linear_model\logistic.py:433: FutureWarning: Default solver will be changed to 'lbfgs' in 0.22. Specify a solver to silence this warning.
  FutureWarning)
C:\ProgramData\Anaconda3\lib\site-packages\sklearn\linear_model\logistic.py:460: FutureWarning: Default multi_class will be changed to 'auto' in 0.22. Specify the multi_class option to silence this warning.
  "this warning.", FutureWarning)
C:\ProgramData\Anaconda3\lib\site-packages\sklearn\linear_model\logistic.py:433: FutureWarning: Default so

0.9533333333333334